# dc-redis cluster

---
apiVersion: v1
data:
  application-kube.properties: |-
    server.port=80
    spring.application.name=dc-redis
    #########redis#########
    spring.redis.database=3
    spring.redis.host=redis-master
    #192.168.50.32
    spring.redis.password=dfws.2017
    spring.redis.port=6379
    spring.redis.pool.max-idle=8
    spring.redis.timeout=10000
    #########eureka############
    eureka.instance.preferIpAddress=true
    eureka.client.registerWithEureka=true
    eureka.client.serviceUrl.defaultZone=http://admin:123456@eureka-0.eureka:80/eureka/,http://admin:123456@eureka-1.eureka:80/eureka/,http://admin:123456@eureka-2.eureka:80/eureka/
kind: ConfigMap
metadata:
  name: redisconfig
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: node1:30400/dc-redis:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: redis-config
          mountPath: /config
      volumes:
      - name: redis-config
        configMap:
          name: redisconfig
---
