# dc-sso cluster
---
kind: Service
apiVersion: v1
metadata:
  name: sso
  labels:
    app: sso
spec:
  selector:
    app: sso
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
data:
  application-kube.properties: |-
    server.port=80
    #########eureka############
    eureka.client.serviceUrl.defaultZone=http://admin:123456@eureka-0.eureka:80/eureka/,http://admin:123456@eureka-1.eureka:80/eureka/,http://admin:123456@eureka-2.eureka:80/eureka/
    eureka.instance.preferIpAddress=true
    eureka.client.registerWithEureka=true
    spring.application.name=dc-sso
    #########greenplum#########
    spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.url=jdbc:postgresql://external-greenplum:2345/md_cloud
    spring.datasource.username=md_cloud
    spring.datasource.password=md_cloud.2017
    spring.datasource.initialSize=5
    spring.datasource.minIdle=5
    spring.datasource.maxActive=20
    spring.datasource.maxWait=60000
    spring.datasource.timeBetweenEvictionRunsMillis=3600000
    #60000
    spring.datasource.minEvictableIdleTimeMillis=18000000
    #300000
    spring.datasource.validationQuery=SELECT 1 FROM DUAL
    spring.datasource.testWhileIdle=true
    spring.datasource.testOnBorrow=true
    spring.datasource.testOnReturn=true
    spring.datasource.poolPreparedStatements=true
    spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
    spring.datasource.filters=stat,wall,log4j
    spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    ###########mybatis#############
    mybatis.mapper-locations=classpath:com/meadin/sso/mapping/*.xml
    ###########sso#############
    #TODO: change below seetings according deployment enviorments
    sso.portrayal.page=http://10.10.50.228:6680/index.html
    sso.sentiment.page=http://10.10.50.228:5089/index.html
    sso.login.page=http://10.10.50.228:6780
kind: ConfigMap
metadata:
  name: ssoconfig
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sso
  labels:
    app: sso
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sso
  template:
    metadata:
      labels:
        app: sso
    spec:
      containers:
      - name: sso
        image: node1:30400/dc-sso:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: sso-config
          mountPath: /config
      volumes:
      - name: sso-config
        configMap:
          name: ssoconfig